#pragma config(Sensor, S3,     colorPort,      sensorCOLORFULL)
#pragma config(Sensor, S4,     irsensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          Right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          Left,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//#include "functions.c"

short nAtoDValues[4];
short nRawValues[4];
short nColorValues[4];


//in this code, we are using the colorRaw values
void displayRGBColorValues()
{
	//short nAtoDValues[4];
	//short nRawValues[4];
	//short nColorValues[4];
	string sTemp;

	getColorSensorData(colorPort, colorAtoD,   nAtoDValues);
	getColorSensorData(colorPort, colorRaw,    nRawValues);
	getColorSensorData(colorPort, colorValue,  nColorValues);

	// displayColorIndex();
wait1Msec(2000);
	nxtDisplayTextLine(3, "   AtoD  Raw   %%");
	StringFormat(sTemp, "R  %4i%5i", nAtoDValues[0], nRawValues[0]);      nxtDisplayTextLine(4, "%s%4i", sTemp, nColorValues[0]);
	StringFormat(sTemp, "G  %4i%5i", nAtoDValues[1], nRawValues[1]);      nxtDisplayTextLine(5, "%s%4i", sTemp, nColorValues[1]);
	StringFormat(sTemp, "B  %4i%5i", nAtoDValues[2], nRawValues[2]);      nxtDisplayTextLine(6, "%s%4i", sTemp, nColorValues[2]);
	StringFormat(sTemp, "Amb%4i%5i", nAtoDValues[3], nRawValues[3]);      nxtDisplayTextLine(7, "%s%4i", sTemp, nColorValues[3]);

}

int finddistance(int r1, int r2, int g1, int g2, int b1, int b2)
{
	int distance=sqrt((r1-r2)*(r1-r2)+(g1-g2)*(g1-g2)+(b1-b2)*(b1-b2));

	return distance;
}



task main()
{

	int colors[][3]=  {
		{129, 50, 47},//red
		{208, 136, 78},//light orange
		{166, 70, 47},//dark orange
		{184, 159, 132},//tan
		{101, 75, 66},//brown
		{207, 186, 117},//light yellow
		{200, 162, 85},//dark yellow
		{160, 190, 111},//light green
		{67, 78, 56},//dark green
		{89, 138, 147},//light blue
		{65, 66, 109},//dark blue
		{116, 170, 93},//purple
		{215, 209, 195},//white
		{203, 77, 88},//pink
		{10, 12, 13}//black
	};

	//
	/*
	rgb values

	r		g		b
	_________
	red
	129 50 47
	light orange
	208 136 78
	dark orange
	166 70 47
	tan
	184 159 132
	brown
	101 75 66
	light yellow
	207 186 117
	dark yellow
	200 162 85
	light green
	160 190 111
	dark green
	67 78 56
	light blue
	89 138 147
	dark blue
	65 66 109
	purple
	116 70 93
	white
	215 209 195
	pink
	203 77 88
	black
	10 12 13


	*/

	while(true)
	{
		displayRGBColorValues();
		wait1Msec(2000);
		//writeDebugStream("RawValue = %d", nRawValues[0]);
		//^^ this statemeent basically shows the past to present values of nRawValues[0] when you open the debugger stream menu
		writeDebugStreamLine("RawValue = %d %d %d", nRawValues[0],nRawValues[1],nRawValues[2]);

		// everything after this point are the different colors and what program they'll lead to if selected
		/*
		//mac and cheese
		if((nRawValues[0]>195 && nRawValues[0]<205) && (nRawValues[1]>140 && nRawValues[1]<148)&& (nRawValues[2]>65 && nRawValues[2]<72))
		{
		goingdownramp();
		break;
		//writeDebugStreamLine("This is Clubhouse");
		}
		//party pink
		if((nRawValues[0]>190 && nRawValues[0]<195) && (nRawValues[1]>130 && nRawValues[1]<135)&& (nRawValues[2]>146 && nRawValues[2]<151))
		{
		knockingdownpole();
		break;
		//writeDebugStreamLine("This is Clubhouse");
		}
		//grapejuice
		if((nRawValues[0]>87 && nRawValues[0]<95) && (nRawValues[1]>45 && nRawValues[1]<55)&& (nRawValues[2]>63 && nRawValues[2]<70))
		{
		goingdownramp();
		knockingdownpole();
		break;
		}

		//clubhouse
		if((nRawValues[0]>35 && nRawValues[0]<45) && (nRawValues[1]>73 && nRawValues[1]<80)&& (nRawValues[2]>53 && nRawValues[2]<60))
		{
		//			testfunction();
		break;
		}

		//carribean sea
		if((nRawValues[0]>40 && nRawValues[0]<48) && (nRawValues[1]>110 && nRawValues[1]<115)&& (nRawValues[2]>135 && nRawValues[2]<140))
		{
		//			testfunction();
		break;
		}

		//orange marmalade
		if((nRawValues[0]>207 && nRawValues[0]<215) && (nRawValues[1]>96 && nRawValues[1]<105)&& (nRawValues[2]>35 && nRawValues[2]<45))
		{
		//			testfunction();
		break;
		}

		//light rail
		if((nRawValues[0]>208 && nRawValues[0]<218) && (nRawValues[1]>175 && nRawValues[1]<185)&& (nRawValues[2]>68 && nRawValues[2]<78))
		{
		//			testfunction();
		break;
		}

		//bluebird
		if((nRawValues[0]>59 && nRawValues[0]<69) && (nRawValues[1]>118 && nRawValues[1]<128)&& (nRawValues[2]>135 && nRawValues[2]<144))
		{
		//			testfunction();
		break;
		}

		//couture
		if((nRawValues[0]>154 && nRawValues[0]<164) && (nRawValues[1]>48 && nRawValues[1]<58)&& (nRawValues[2]>45 && nRawValues[2]<55))
		{
		//			testfunction();
		break;
		}

		//blue cirque
		if((nRawValues[0]>28 && nRawValues[0]<37) && (nRawValues[1]>47 && nRawValues[1]<55)&& (nRawValues[2]>59 && nRawValues[2]<68))
		{
		//			testfunction();
		break;
		}

		//dandy lion
		if((nRawValues[0]>182 && nRawValues[0]<195) && (nRawValues[1]>137 && nRawValues[1]<148)&& (nRawValues[2]>65 && nRawValues[2]<75))
		{
		//			testfunction();
		break;
		}

		//hw10
		if((nRawValues[0]>143 && nRawValues[0]<153) && (nRawValues[1]>180 && nRawValues[1]<190)&& (nRawValues[2]>62 && nRawValues[2]<73))
		{
		//			testfunction();
		break;
		}

		//fresh foliage
		if((nRawValues[0]>28 && nRawValues[0]<38) && (nRawValues[1]>47 && nRawValues[1]<58)&& (nRawValues[2]>48 && nRawValues[2]<56))
		{
		//			testfunction();
		break;
		}

		//bright black raspberry
		if((nRawValues[0]>118 && nRawValues[0]<128) && (nRawValues[1]>40 && nRawValues[1]<45)&& (nRawValues[2]>42 && nRawValues[2]<52))
		{
		//			testfunction();
		break;
		}

		//new grass green
		if((nRawValues[0]>103 && nRawValues[0]<113) && (nRawValues[1]>165 && nRawValues[1]<175)&& (nRawValues[2]>79 && nRawValues[2]<89))
		{
		//			testfunction();
		break;
		}

		//dewy iris
		if((nRawValues[0]>115 && nRawValues[0]<125) && (nRawValues[1]>113 && nRawValues[1]<123)&& (nRawValues[2]>131 && nRawValues[2]<140))
		{
		//			testfunction();
		break;
		}
		*/
	}
}
