#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     elevator1,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     elevator2,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    score,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"



task main()
{
	int scoreopen = 5;
	int scoreclose = 245;
	int threshold = 40;
	while(true)
	{
		getJoystickSettings(joystick); //Constantly updates values on the joystick

		nMotorEncoder[elevator1]=0;
		nMotorEncoder[elevator2]=0;

		disableDiagnosticsDisplay();
		nxtDisplayTextLine(1,"%d", nMotorEncoder[elevator1]);
		nxtDisplayTextLine(2,"%d", nMotorEncoder[elevator2]);

		if((joystick.joy1_y2) > threshold)
		{
			motor[elevator1]= 100;//Raises the elevator
			motor[elevator2]= 100;
		}
		else if((joystick.joy1_y2) < -threshold && SensorValue(touch)==0)
		{
			motor[elevator1]=-100;
			motor[elevator2]=-100;
		}
		else
		{
			motor[elevator1]=0;
			motor[elevator2]=0;
		}


	}






}
