#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTServo,  HTServo)
#pragma config(Sensor, S3,     compass,         sensorI2CCustom)
#pragma config(Sensor, S4,     Mux,            sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C1_1,     RightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightBack,     tmotorTetrix, openLoop,)
#pragma config(Motor,  mtr_S2_C1_1,     elevator1,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     elevator2,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     LeftFront,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     LeftBack,      tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    frontRS,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    backRS,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    lock,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_1,    frontLS,              tServoStandard)
#pragma config(Servo,  srvo_S2_C3_2,    backLS,               tServoStandard)
#pragma config(Servo,  srvo_S2_C3_3,    score,                tServoStandard)
#pragma config(Servo,  srvo_S2_C3_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C3_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C3_6,    servo12,              tServoNone)
#pragma config(Servo,  srvo_S2_C4_1,    leftmandible,         tServoStandard)
#pragma config(Servo,  srvo_S2_C4_2,    rightmandible,        tServoStandard)
#pragma config(Servo,  srvo_S2_C4_3,    mouth,                tServoStandard)
#pragma config(Servo,  srvo_S2_C4_4,    gate,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C4_5,    servo23,              tServoNone)
#pragma config(Servo,  srvo_S2_C4_6,    servo24,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//swapped backRS and front RS
#include "hitechnic-irseeker-v2.h";//3rd party driver for the ir sensor
//#include "JoystickDriver.c"
#include "hitechnic-sensormux.h"
#include "hitechnic-compass.h"
#include "lego-touch.h"
//#include "swerve functions v2.h"
#include "hitechnic-eopd.h"


#define touch msensor_S4_2
#define HTIRS2 msensor_S4_4
#define colorport msensor_S4_1
#define eopd msensor_S4_3


task main()
{
	HTEOPDsetShortRange(eopd);

	int under=0;
	/*
	0 means nothing underneath
	1 means something new underneath
	2 means something has been underneath
	*/
	int eopdthreshold=16;


	while(true)
	{

		nxtDisplayCenteredTextLine(3, "eopd:%d", HTEOPDreadProcessed(eopd));
	if(HTEOPDreadProcessed(eopd)>eopdthreshold)
	{
		under=0;
	}
	else if(HTEOPDreadProcessed(eopd)< eopdthreshold && under==0)
	{
		under=1;
	}
	else
	{
		under=2;
	}

		switch(under)
		{
	case 0:	nxtDisplayCenteredTextLine(4, "Nothing");	break;
	case 1:	nxtDisplayCenteredTextLine(4, "Something New"); PlaySound(soundBeepBeep); PlaySound(soundBeepBeep); break;
	case 2:	nxtDisplayCenteredTextLine(4, "Something Old");	break;
	}

	wait1Msec(2000);

	}


}
