#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTServo,  HTServo)
#pragma config(Sensor, S3,     compass,         sensorI2CCustom)
#pragma config(Sensor, S4,     Mux,            sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C1_1,     RightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightBack,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     elevator1,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     elevator2,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     LeftFront,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     LeftBack,      tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    frontRS,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    backRS,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    lock,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_1,    frontLS,              tServoStandard)
#pragma config(Servo,  srvo_S2_C3_2,    backLS,               tServoStandard)
#pragma config(Servo,  srvo_S2_C3_3,    score,                tServoStandard)
#pragma config(Servo,  srvo_S2_C3_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C3_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C3_6,    servo12,              tServoNone)
#pragma config(Servo,  srvo_S2_C4_1,    leftmandible,         tServoStandard)
#pragma config(Servo,  srvo_S2_C4_2,    rightmandible,        tServoStandard)
#pragma config(Servo,  srvo_S2_C4_3,    mouth,                tServoStandard)
#pragma config(Servo,  srvo_S2_C4_4,    gate,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C4_5,    servo23,              tServoNone)
#pragma config(Servo,  srvo_S2_C4_6,    servo24,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define HTIRS2 msensor_S4_4
#define colorport msensor_S4_1

#include "hitechnic-sensormux.h" //THIS MUST BE THE FIRST #INCLUDE
#include "hitechnic-irseeker-v2.h"//3rd party driver for the ir sensor
#include "joystickdriver.c"
#include "hitechnic-compass.h"
#include "hitechnic-colour-v2.h"
//#include "hitechnic-colour-v1.h"
#include "..\..\autonomous variables.h"
#include "..\..\swerve functions.h"
#include "..\..\swerve autonomous functions.h"
#include "..\..\Autonomous Routines.h"
//.. means go up a directory
//these are in the github directory
//default driver location is c:\~~github directory~~\2014\rdpartyrobotcdr-3.3.1\drivers
//programs are located in c:\~~github directory~~\2014
//so we have to go up 2 directories to get to \2014 from \rdpartyrobotcdr-3.3.1\drivers




//----------------------------------------------------------------------------START TASK MAIN---------------------------------------------
task main()
{
	//	clearDebugStream();
	//waitForStart();
	/*
	list of programs

	starting		|what to
	position		|do
	______________________________
	1		ramp		|drop ball in small goal and move to parking
	2		parking	|drop ball in small goal and move to parking//values not tested
	3		parking	|score in center goal
	4		parking	|knocks down kickstand
	5		parking	|messes up oponents rolling goals
	6						|
	7		parking	|get in way of opponent 120 goal
	8						|
	9						|
	10					|
	11	ramp		|drop ball in small goal and move to parking(with compass)
	12	parking	|drop ball in small goal and move to parking//values not tested
	13					|
	14					|
	15	anywhere|go straight 6 feet (can get of ramp)
	21	ramp		|drop ball in small goal and move to parking (BACKWARDS)




	3|lightblue//program1
	3|darkblue
	5|darkyellow
	7|pink
	7|red//program3
	7|orange
	13|lightgreen
	14|white//program11
	14|tan
	14|brown
	14|lightyellow
	17|purple
	17|black//default(program15)



	*/



	//wait1Msec(2000);
	//	disableDiagnosticsDisplay();
	short colorValues[4];//these are the scanned values

	int j;
	long r;
	long g;
	long b;
	//	wait1Msec(500);

	int minDifference = 32767; // MAX_INT
	int selectedColor = 0;//this is the color closest to the scanned color
	servo[gate]=gateup;


	// gostraight

	sFRS = 161;
	sBRS = 154;
	sFLS = 132;
	sBLS = 131;

	servo[frontRS]= sFRS;
	servo[backRS]= sBRS;
	servo[frontLS]= sFLS;
	servo[backLS]= sBLS;
	wait1Msec(500);


	//servo[leftmandible] = outL;
	//servo[rightmandible] = outR;
	//	servo[mouth] = mouthup;
	servo[score] = scoreclose;
	servo[lock] = lockup;
	servo[gate] = gateup;
	servo[mouth]= mouthup;
	selectedColor=HTCS2readColor(colorport);
	selectedColor=HTCS2readColor(colorport);
	selectedColor=HTCS2readColor(colorport);
	selectedColor=HTCS2readColor(colorport);

	turnServos(1,0);


	clearDebugStream();

while(true){godirection(1,120);}
}
