#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTServo,  HTServo)
#pragma config(Sensor, S3,     GYRO,         sensorI2CCustom)
#pragma config(Sensor, S4,     Mux,            sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C1_1,     RightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightBack,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     elevator1,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     elevator2,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     LeftFront,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     LeftBack,      tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    frontRS,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    backRS,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    lock,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_1,    frontLS,              tServoStandard)
#pragma config(Servo,  srvo_S2_C3_2,    backLS,               tServoStandard)
#pragma config(Servo,  srvo_S2_C3_3,    score,                tServoStandard)
#pragma config(Servo,  srvo_S2_C3_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C3_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C3_6,    servo12,              tServoNone)
#pragma config(Servo,  srvo_S2_C4_1,    leftmandible,         tServoStandard)
#pragma config(Servo,  srvo_S2_C4_2,    rightmandible,        tServoStandard)
#pragma config(Servo,  srvo_S2_C4_3,    mouth,                tServoStandard)
#pragma config(Servo,  srvo_S2_C4_4,    gate,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C4_5,    servo23,              tServoNone)
#pragma config(Servo,  srvo_S2_C4_6,    servo24,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define touch msensor_S4_2
#define HTIRS2 msensor_S4_4
#define eopd1 msensor_S4_3
#define ultrasound msensor_S4_1
#define eopd2 msensor_S4_1
#define USING_2_EOPD 1


#define NUMBER_OF_PROGRAMS 31



#include "hitechnic-sensormux.h" //THIS MUST BE THE FIRST #INCLUDE
#include "hitechnic-irseeker-v2.h"//3rd party driver for the ir sensor
#include "joystickdriver.c"
#include "hitechnic-compass.h"
#include "hitechnic-colour-v2.h"
#include "hitechnic-gyro.h"
#include "hitechnic-eopd.h"
#include "lego-ultrasound.h"
#include "..\..\autonomous variables.h"
#include "..\..\swerve functions v2.h"
#include "..\..\swerve autonomous functions.h"
#include "..\..\Autonomous Routines v3.h"
//.. means go up a directory
//these are in the github directory
//default driver location is c:\~~github directory~~\2014\rdpartyrobotcdr-3.3.1\drivers
//programs are located in c:\~~github directory~~\2014
//so we have to go up 2 directories to get to \2014 from \rdpartyrobotcdr-3.3.1\drivers




//----------------------------------------------------------------------------START TASK MAIN---------------------------------------------
task main()
{
	//	clearDebugStream();
	//waitForStart();
	/*
	list of programs

	starting		|what to
	position		|do
	______________________________
	1		ramp		|drop ball in small goal and move to parking
	2		parking	|drop ball in small goal and move to parking//values not tested
	3		parking	|score in center goal
	4			      |
	5						|
	6						|
	7						|
	8						|
	9		parking	|knocks down kickstand
	10	ramp		|scores in mid and knocks kickstand(With IR)
	11	ramp		|drop ball in small goal and move to parking(with compass)
	12	parking	|drop ball in small goal and move to parking//values not tested
	13					|
	14					|
	15	anywhere|go straight 6 feet (can get of ramp)
	21	ramp		|drop ball in small goal and move to parking (BACKWARDS)
	*/
	//wait1Msec(2000);
	//	disableDiagnosticsDisplay();

	//	wait1Msec(500);






	HTEOPDsetShortRange(eopd1);
	HTEOPDsetShortRange(eopd2);




	servo[gate]=gateup;


	// gostraight

	sFRS = 161;
	sBRS = 154;
	sFLS = 132;
	sBLS = 131;

	servo[frontRS]= sFRS;
	servo[backRS]= sBRS;
	servo[frontLS]= sFLS;
	servo[backLS]= sBLS;
	wait1Msec(500);


	//servo[leftmandible] = outL;
	//servo[rightmandible] = outR;
	//	servo[mouth] = mouthup;
	servo[score] = scoreclose;
	servo[lock] = lockup;
	servo[gate] = gateup;
	servo[mouth]= mouthup;


	turnServos(1,0);








	while(true)
	{

		if(nNxtButtonPressed==1)//move wheel position back
		{//right button

			selectprgm++;
			if(selectprgm<0)
			{

				selectprgm+=(NUMBER_OF_PROGRAMS+1);
			}
			if(selectprgm>NUMBER_OF_PROGRAMS)
			{

				selectprgm-=NUMBER_OF_PROGRAMS;
			}
			nxtDisplayCenteredTextLine(2,"program%d",selectprgm);

			wait1Msec(500);
		}
		// lower elevator
		else if(nNxtButtonPressed==2)//move wheel position forward
		{//left button

			selectprgm--;
			if(selectprgm<1)
			{

				selectprgm+=NUMBER_OF_PROGRAMS;
			}
			if(selectprgm>5)
			{

				selectprgm-=NUMBER_OF_PROGRAMS;
			}

			nxtDisplayCenteredTextLine(2,"program%d",selectprgm);
			wait1Msec(500);
		}

		if(nNxtButtonPressed==3)//not tested yet is either 0 or 3 depending on what number the center button is for
		{
			break;
		}

}

	turnServos(1,0);


	wait1Msec(3000);
	PlaySound(soundBeepBeep);
	PlaySound(soundBeepBeep);

//		waitForStart();
	servo[gate]=gatedrive;



switch(selectprgm)
		{
		case 1: program1(); break;
		case 2: program2();	break;
		//case 3: program3(); break;
		//case 4: program4();	break;
		//case 5: program5();	break;
		//case 6: program6();	break;
		//case 7: program7();	break;
		//case 8: program8();	break;
		case 9: program9();	break;
		case 10: program10();	break;
		//case 11: program11();	break;
		case 12: program12();	break;
		//case 13: program13();	break;
		//case 14: program14();	break;
		case 15: program15();	break;
		//case 16: program16();	break;
		//case 17: program17();	break;
		//case 18: program18();	break;
		//case 19: program19();	break;
		//case 20: program20();	break;
		case 21: program21();	break;
		case 22: program22();	break;
		//case 23: program23();	break;
		//case 24: program24();	break;
		//case 25: program25();	break;
		//case 26: program26();	break;
		//case 27: program27();	break;
		//case 28: program28();	break;
		//case 29: program29();	break;
		//case 30: program30();	break;
		case 31: program31();	break;
		default: program15(); break;
		}

	//program1();

	//turnleft90();
	//compassturn(180);
	//compassturn(180);
	//while(true);
	//program1();
	//turnServos(2,0);
	//wait1Msec(5000);
	program9();





}
