#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S4,     HTIRS2,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     RightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightBack,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     LeftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     LeftBack,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servo7,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h";
void turn90()
{
	int speed=50;
	int threshold=1440*3*PI/4;

	nMotorEncoder[RightBack] = 0;
	nMotorEncoder[RightFront] = 0;
	nMotorEncoder[LeftBack] = 0;
	nMotorEncoder[LeftFront] = 0;
	while(nMotorEncoder[RightBack] < threshold && nMotorEncoder[LeftFront] > -threshold)
	{
		motor[RightFront] = speed;
		motor[RightBack] = speed;
		motor[LeftFront] = -speed;
		motor[LeftBack] = -speed;
	}
	motor[RightFront] = 0;
	motor[RightBack] = 0;
	motor[LeftFront] = 0;
	motor[LeftBack] = 0;


}

void turn45()
{
	int speed=50;
	int threshold=1440*3*PI/8;

	nMotorEncoder[RightBack] = 0;
	nMotorEncoder[RightFront] = 0;
	nMotorEncoder[LeftBack] = 0;
	nMotorEncoder[LeftFront] = 0;
	while(nMotorEncoder[RightBack] < threshold && nMotorEncoder[LeftFront] > -threshold)
	{
		motor[RightFront] = speed;
		motor[RightBack] = speed;
		motor[LeftFront] = -speed;
		motor[LeftBack] = -speed;
	}
	motor[RightFront] = 0;
	motor[RightBack] = 0;
	motor[LeftFront] = 0;
	motor[LeftBack] = 0;


}




/*
int turndegree( int degree)
{


int speed=50;
motor[RightFront] = speed;
motor[RightBack] = speed;
motor[LeftFront] = -speed;
motor[LeftBack] = -speed;
wait1Msec(degree*2400/90);

return 0;
}
*/

task main()
{
	int speed = 50;
	int fullspeed = 100;
	int position = 2;//this is the position of the centerpiece. can be 1, 2, or 3
	int acS1, acS2, acS3, acS4, acS5;
	int acS1avg=0, acS2avg=0, acS3avg=0, acS4avg=0, acS5avg=0;
	int prevacS1, prevacS2, prevacS3, prevacS4, prevacS5;
	int irthreshold=58.5;

	/*
	position 1 ir readings
	acs1 1 acs2 1 acs3 1 acs4 1 acs5 1

	position 2 ir readings
	acs1 0 acs2 0 acs3 0 acs4 32 acs5 0

	position 3 ir readings
	acs1 0 acs2 0 acs3 0 acs4 85 acs5 0

	*/
/*
	while(true)
	{
		HTIRS2readAllACStrength(HTIRS2,  acS1, acS2, acS3, acS4, acS5);
		acS1avg=(prevacS1+acS1)/2;
		acS2avg=(prevacS2+acS2)/2;
		acS3avg=(prevacS3+acS3)/2;
		acS4avg=(prevacS4+acS4)/2;
		acS5avg=(prevacS5+acS5)/2;
		writeDebugStreamLine("acs1 %d acs2 %d acs3 %d acs4 %d acs5 %d ",acS1avg, acS2avg, acS3avg, acS4avg, acS5avg);
		wait1Msec(250);
		prevacS1=acS1;
		prevacS2=acS2;
		prevacS3=acS3;
		prevacS4=acS4;
		prevacS5=acS5;
	}
*/

	motor[RightFront] = speed;
	motor[RightBack] = speed;
	motor[LeftFront] = speed;
	motor[LeftBack] = speed;
	wait1Msec(2600);

	HTIRS2readAllACStrength(HTIRS2,  acS1, acS2, acS3, acS4, acS5);

	if(acS4>irthreshold)
{
position=3;
}
else
{
position=2;
}

if(position==1 || position==2)
{
	motor[RightFront] = speed;
	motor[RightBack] = speed;
	motor[LeftFront] = speed;
	motor[LeftBack] = speed;
	wait1Msec(500);

	turn90();


	motor[RightFront] = speed;
	motor[RightBack] = speed;
	motor[LeftFront] = speed;
	motor[LeftBack] = speed;
	wait1Msec(1500);

	turn45();

	motor[RightFront] = fullspeed;
	motor[RightBack] = fullspeed;
	motor[LeftFront] = fullspeed;
	motor[LeftBack] = fullspeed;
	wait1Msec(1000);

	turn45();
}
else if(position == 3)
{
	motor[RightFront] = speed;
	motor[RightBack] = speed;
	motor[LeftFront] = speed;
	motor[LeftBack] = speed;
	wait1Msec(4000);


	motor[RightFront] = speed;
	motor[RightBack] = speed;
	motor[LeftFront] = -speed;
	motor[LeftBack] = -speed;
	wait1Msec(5000);

	motor[RightFront] = fullspeed;
	motor[RightBack] = fullspeed;
	motor[LeftFront] = fullspeed;
	motor[LeftBack] = fullspeed;
	wait1Msec(3000);


}
}
