#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     spinner,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     sweeper,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    toppiece,             tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
/*
TO DO
structs
state engine

DONE
add different positions for toppiece
add different motor speeds for spinner
30
100



*/

/*
KEY CONFIGS
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!IN THE PROGRAM IT STARTS AT 1!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

0							|
1							|set toppiece to 0
2							|
3							|set toppiece to 215
4							|conveyerbelt=100
5							|sweeper=100 Backward
6							|conveyerbelt=30
7							|sweeper=-100 Forward
8							|
9							|
LeftCircle		|RightMotor
RightCircle		|LeftMotor
Arrow0				|
Arrow1				|
Arrow2				|
Arrow3				|
Arrow4				|
Arrow5				|
Arrow6				|
Arrow7				|
*/
task main()
{
	int threshold = 20;
	waitForStart();
	while(true)
	{
		//motor[sweeper]=-50;
		getJoystickSettings(joystick);  									//Constantly updates values on the joystick

		//Right Wheel

		if(abs(joystick.joy1_y1) > threshold)
		{
			motor[Right] = joystick.joy1_y1;
		}
		else
		{
			motor[Right] = 0;
		}

		//Left wheel

		if (abs(joystick.joy1_y2) > threshold)
		{
			motor[Left] = joystick.joy1_y2;
		}
		else
		{
			motor[Left] = 0;
		}
		//the conveyer belt------------------------------------------
		if(joy1Btn(7))
		{
			//  sPIN sLOW
			motor[spinner] = 30;
			//wait1Msec(50);
		}
		else if(joy1Btn(5))
		{
			motor[spinner] = 100;
		}
		else
		{
			motor[spinner] = 0;
		}



		//Everything with servo[toppiece] is for the dinosaur head
		if(joy1Btn(4))
		{
			servo[toppiece] = 215;
		}

		if(joy1Btn(2))
		{
			servo[toppiece] = 0;
		}


		//Sweeper
		if(joy1Btn(6))
		{
			motor[sweeper]=-100;
		}
		else if(joy1Btn(8))
		{
	motor[sweeper]=100;
		}
	}
}
