#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     spinner,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    rollgoal,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
``
#include "JoystickDriver.c"

task main()
{
	// servo settings
	;
	int rollgoal_up = 90/*210*/;
	int rollgoal_down = 40;
	servo[rollgoal]=180;



	int threshold = 20;
	waitForStart();
	while(true)
	{
		getJoystickSettings(joystick);
		//Constantly updates values on the joystick

		//Right Wheel

		if(abs(joystick.joy1_y1) > threshold)
		{
			motor[Right] = (joystick.joy1_y1);
		}
		else
		{
			motor[Right] = 0;
		}

		//Left wheel

		if (abs(joystick.joy1_y2) > threshold)
		{
			motor[Left] = (joystick.joy1_y2);
		}
		else
		{
			motor[Left] = 0;
		}

		// latch rolling goal

		if(joy1Btn(2))
		{

			servo[rollgoal] = rollgoal_down;
			wait1Msec(500);
				//motor[Right] = -40;
				//motor[Left] = -40;
				wait1Msec(250);
				servo[rollgoal] = rollgoal_down - 10;
				//motor[Right] = 0;
				//motor[Left] = 0;
				wait1Msec(500);  /// let go of button!!!


		}

		// lets go of rolling goal

		if(joy1Btn(4))
		{

			servo[rollgoal] = rollgoal_up;
			wait1Msec(200);
		}
		//  SPINNER
		if(joy1Btn(5))
		{
			//  sPIN FAST

			motor[spinner] = -100;
			wait1Msec(50);
		}
		else
		{

			motor[spinner] = 0;

		}

		if(joy1Btn(7))
		{
			//  sPIN sLOW

			motor[spinner] = -60;
				wait1Msec(50);
		}
		else
		{

			motor[spinner] = 0;

		}

	}

}
