#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTServo,  HTServo)
#pragma config(Sensor, S3,     compass,         sensorI2CCustom)
#pragma config(Sensor, S4,     Mux,            sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C1_1,     RightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightBack,     tmotorTetrix, openLoop,)
#pragma config(Motor,  mtr_S2_C1_1,     elevator1,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     elevator2,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     LeftFront,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     LeftBack,      tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    frontRS,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    backRS,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    lock,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_1,    frontLS,              tServoStandard)
#pragma config(Servo,  srvo_S2_C3_2,    backLS,               tServoStandard)
#pragma config(Servo,  srvo_S2_C3_3,    score,                tServoStandard)
#pragma config(Servo,  srvo_S2_C3_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C3_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C3_6,    servo12,              tServoNone)
#pragma config(Servo,  srvo_S2_C4_1,    leftmandible,         tServoStandard)
#pragma config(Servo,  srvo_S2_C4_2,    rightmandible,        tServoStandard)
#pragma config(Servo,  srvo_S2_C4_3,    mouth,                tServoStandard)
#pragma config(Servo,  srvo_S2_C4_4,    gate,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C4_5,    servo23,              tServoNone)
#pragma config(Servo,  srvo_S2_C4_6,    servo24,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h";//3rd party driver for the ir sensor
#include "joystickdriver.c"
#include "hitechnic-sensormux.h"    //Use the path where you put Xander's drivers
#include "hitechnic-compass.h"
#include "lego-touch.h"
#include "..\..\swerve functions.h"
//#include "swerve functions.c"





task main()
{

	int mouthdown=214;

	disableDiagnosticsDisplay();
	eraseDisplay();
	nxtDisplayCenteredBigTextLine(1,"Wheel");
	nxtDisplayCenteredBigTextLine(3,"Mover");



	int x=1;

	int wheel=1;

	turnServos(1,0);


	while(true)
		{

		if(nNxtButtonPressed==1)
		{//right button

		wheel++;
			if(wheel<1)
			{

				wheel+=4;
			}
			if(wheel>4)
			{

				wheel-=4;
			}

			wait1Msec(300);
		}
		// lower elevator
		else if(nNxtButtonPressed==2)
		{//left button

		wheel--;
			if(wheel<1)
			{

				wheel+=4;
			}
			if(wheel>4)
			{

				wheel-=4;
			}
			wait1Msec(300);

	`	}



		if(nNxtButtonPressed==3)
		{//middle button
			break;
		}


		//nxtDisplayCenteredTextLine(6,"%d",wheel);
		switch(wheel)
		{
	case 1:		nxtDisplayCenteredTextLine(6,"FrontLeft"); break;
	case 2:		nxtDisplayCenteredTextLine(6,"BackLeft"); break;
	case 3:		nxtDisplayCenteredTextLine(6,"FrontRight"); break;
	case 4:		nxtDisplayCenteredTextLine(6,"BackRight"); break;
	}

		}



		switch(wheel)
		{
	case 1:		nxtDisplayCenteredBigTextLine(6,"FrontLeft"); break;
	case 2:		nxtDisplayCenteredBigTextLine(6,"BackLeft"); break;
	case 3:		nxtDisplayCenteredBigTextLine(6,"FrontRight"); break;
	case 4:		nxtDisplayCenteredBigTextLine(6,"BackRight"); break;
	}


	while(true)
	{



		if(nNxtButtonPressed==1 && x>0)//move wheel position back
		{//right button

						x++;





		}
		// lower elevator
		else if(nNxtButtonPressed==2 && x<254)//move wheel position forward
		{//left button

			x--;
			if(x<1)
			{

				x+=5;
			}


			turnServos(x,0);
			wait1Msec(500);
		}


		nxtDisplayCenteredTextLine(5,"Servo Value:%d",x);

	}


	}



}
