#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



void forward(int distance)//distance in centimeters
{
	int mtrspd=100;
	int circumference=40;// wheel circumference  is 40 cm
	int revolutions=distance/circumference; //distance = revolutions * circumference


	nMotorEncoder(motorD)=0;
	nMotorEncoder(motorE)=0;

	while(nMotorEncoder(motorD)<=revolutions*360 && nMotorEncoder(motorE)<=revolutions*360)//45 degree turn to the right
	{
		motor(motorD)=-mtrspd;//motorD is backward
		motor(motorE)=mtrspd;
	}
	return;
}




task main()
{
	int mtrspd=100;//motor speed
	nMotorEncoder(motorD)=0;
	nMotorEncoder(motorE)=0;


	int x=nMotorEncoder(motorD), y=nMotorEncoder(motorE);

	forward(2000);

//	motor(motorD)=-mtrspd;
//	motor(motorE)=mtrspd;
//	wait10Msec(300);



	nMotorEncoder(motorD)=0;
	nMotorEncoder(motorE)=0;

	while(nMotorEncoder(motorD)>=-360 && nMotorEncoder(motorE)>=-270)//45 degree turn to the right
	{
		motor(motorD)=mtrspd;//turn because motorD is backward
		motor(motorE)=mtrspd;
		x=nMotorEncoder(motorD);
		y=nMotorEncoder(motorE);
		wait10Msec(300);
	}


	motor(motorD)=-mtrspd;
	motor(motorE)=mtrspd;
	wait10Msec(200);


	nMotorEncoder(motorD)=0;
	nMotorEncoder(motorE)=0;

	while(nMotorEncoder(motorD)<=360 && nMotorEncoder(motorE)<=270)//45 degree turn to the right
	{
		motor(motorD)=-mtrspd;//turn because motorD is backward
		motor(motorE)=-mtrspd;
		x=nMotorEncoder(motorD);
		y=nMotorEncoder(motorE);
		wait10Msec(300);
	}



	motor(motorD)=-mtrspd;
	motor(motorE)=mtrspd;
	wait10Msec(300);



	while(nMotorEncoder(motorD)<=1440 && nMotorEncoder(motorE)<=1080)//180 degree turn
	{
		motor(motorD)=-mtrspd;//turn because motorD is backward
		motor(motorE)=-mtrspd;
		x=nMotorEncoder(motorD);
		y=nMotorEncoder(motorE);
		wait10Msec(300);
	}

	servo[servo1]=0;















}
